export default [
  {
    version: null,
    resourceId: 1001,
    value: 1001,
    resourceIcon: null,
    resourceKey: 'store',
    resourceName: 'Store',
    title: 'Store',
    resourceStatus: 0,
    resourceStatusText: '正常',
    resourceUrl: '/store',
    orderNum: 0,
    parentId: 0,
    children: null,
    resourceType: 0,
    resourceTypeText: '页面',
  },
  {
    version: null,
    resourceId: 1002,
    value: 1002,
    resourceIcon: null,
    resourceKey: 'category',
    resourceName: 'Category',
    title: 'Category',
    resourceStatus: 0,
    resourceStatusText: '正常',
    resourceUrl: '/category',
    orderNum: 0,
    parentId: 0,
    children: null,
    resourceType: 0,
    resourceTypeText: '页面',
  },
  {
    version: null,
    resourceId: 1002,
    value: 1002,
    resourceIcon: null,
    resourceKey: 'goods',
    resourceName: 'Goods',
    title: 'Goods',
    resourceStatus: 0,
    resourceStatusText: '正常',
    resourceUrl: '/goods',
    orderNum: 0,
    parentId: 0,
    children: null,
    resourceType: 0,
    resourceTypeText: '页面',
  },

  {
    version: null,
    resourceId: 1003,
    value: 1003,
    resourceIcon: null,
    resourceKey: 'country',
    resourceName: 'Country',
    title: 'Country',
    resourceStatus: 0,
    resourceStatusText: '正常',
    resourceUrl: '/country',
    orderNum: 0,
    parentId: 0,
    children: null,
    resourceType: 0,
    resourceTypeText: '页面',
  },
  {
    version: null,
    resourceId: 1004,
    value: 1004,
    resourceIcon: null,
    resourceKey: 'rank',
    resourceName: 'Rank',
    title: 'Rank',
    resourceStatus: 0,
    resourceStatusText: '正常',
    resourceUrl: '/rank',
    orderNum: 0,
    parentId: 0,
    children: null,
    resourceType: 0,
    resourceTypeText: '页面',
  },
  // {
  //   version: null,
  //   resourceId: 28,
  //   value: 28,
  //   resourceIcon: null,
  //   resourceKey: 'home',
  //   resourceName: 'Home',
  //   title: 'Home',
  //   resourceStatus: 0,
  //   resourceStatusText: '正常',
  //   resourceUrl: '/Home',
  //   orderNum: 0,
  //   parentId: 0,
  //   children: null,
  //   resourceType: 0,
  //   resourceTypeText: '页面',
  // },
  // {
  //   version: null,
  //   resourceId: 29,
  //   value: 29,
  //   resourceIcon: null,
  //   resourceKey: 'product',
  //   resourceName: 'Product Management',
  //   title: 'Product Management',
  //   resourceStatus: 0,
  //   resourceStatusText: '正常',
  //   resourceUrl: '/',
  //   orderNum: 1,
  //   parentId: 0,
  //   children: [
  //     {
  //       version: null,
  //       resourceId: 30,
  //       value: 30,
  //       resourceIcon: null,
  //       resourceKey: 'productAdd',
  //       resourceName: 'Add Product',
  //       title: 'Add Product',
  //       resourceStatus: 0,
  //       resourceStatusText: '正常',
  //       resourceUrl: '/ProductManagement/AddProduct',
  //       orderNum: 0,
  //       parentId: 29,
  //       children: null,
  //       resourceType: 0,
  //       resourceTypeText: '页面',
  //     },
  //     {
  //       version: null,
  //       resourceId: 141,
  //       value: 141,
  //       resourceIcon: null,
  //       resourceKey: 'productEdit',
  //       resourceName: 'Edit Product',
  //       title: 'Edit Product',
  //       resourceStatus: 0,
  //       resourceStatusText: '正常',
  //       resourceUrl: null,
  //       orderNum: 0,
  //       parentId: 29,
  //       children: null,
  //       resourceType: 0,
  //       resourceTypeText: '页面',
  //     },
  //     {
  //       version: null,
  //       resourceId: 142,
  //       value: 142,
  //       resourceIcon: null,
  //       resourceKey: 'productDetail',
  //       resourceName: 'Product Detail',
  //       title: 'Product Detail',
  //       resourceStatus: 0,
  //       resourceStatusText: '正常',
  //       resourceUrl: null,
  //       orderNum: 0,
  //       parentId: 29,
  //       children: null,
  //       resourceType: 0,
  //       resourceTypeText: '页面',
  //     },
  //     {
  //       version: null,
  //       resourceId: 31,
  //       value: 31,
  //       resourceIcon: null,
  //       resourceKey: 'productList',
  //       resourceName: 'My Product',
  //       title: 'My Product',
  //       resourceStatus: 0,
  //       resourceStatusText: '正常',
  //       resourceUrl: '/ProductManagement/MyProduct',
  //       orderNum: 1,
  //       parentId: 29,
  //       children: null,
  //       resourceType: 0,
  //       resourceTypeText: '页面',
  //     },
  //     {
  //       version: null,
  //       resourceId: 32,
  //       value: 32,
  //       resourceIcon: null,
  //       resourceKey: 'groupList',
  //       resourceName: 'Category Group',
  //       title: 'Category Group',
  //       resourceStatus: 0,
  //       resourceStatusText: '正常',
  //       resourceUrl: '/ProductManagement/CategoryGroup',
  //       orderNum: 2,
  //       parentId: 29,
  //       children: null,
  //       resourceType: 0,
  //       resourceTypeText: '页面',
  //     },
  //     {
  //       version: null,
  //       resourceId: 143,
  //       value: 143,
  //       resourceIcon: null,
  //       resourceKey: 'groupDetail',
  //       resourceName: 'Group Detail',
  //       title: 'Group Detail',
  //       resourceStatus: 0,
  //       resourceStatusText: '正常',
  //       resourceUrl: null,
  //       orderNum: 2,
  //       parentId: 29,
  //       children: null,
  //       resourceType: 0,
  //       resourceTypeText: '页面',
  //     },
  //   ],
  //   resourceType: 0,
  //   resourceTypeText: '页面',
  // },
  // {
  //   version: null,
  //   resourceId: 410,
  //   value: 410,
  //   resourceIcon: 'smile',
  //   resourceKey: 'inquiry',
  //   resourceName: 'Inquiry Management',
  //   title: 'Inquiry Management',
  //   resourceStatus: 0,
  //   resourceStatusText: '正常',
  //   resourceUrl: '/inquiry',
  //   orderNum: 2,
  //   parentId: 0,
  //   children: null,
  //   resourceType: 0,
  //   resourceTypeText: '页面',
  // },
  // {
  //   version: null,
  //   resourceId: 36,
  //   value: 36,
  //   resourceIcon: null,
  //   resourceKey: 'rfq',
  //   resourceName: 'RFQ Management',
  //   title: 'RFQ Management',
  //   resourceStatus: 0,
  //   resourceStatusText: '正常',
  //   resourceUrl: '/RFQManagement',
  //   orderNum: 3,
  //   parentId: 0,
  //   children: [
  //     {
  //       version: null,
  //       resourceId: 144,
  //       value: 144,
  //       resourceIcon: null,
  //       resourceKey: 'rfqList',
  //       resourceName: 'RFQ List',
  //       title: 'RFQ List',
  //       resourceStatus: 0,
  //       resourceStatusText: '正常',
  //       resourceUrl: null,
  //       orderNum: 0,
  //       parentId: 36,
  //       children: null,
  //       resourceType: 0,
  //       resourceTypeText: '页面',
  //     },
  //     {
  //       version: null,
  //       resourceId: 145,
  //       value: 145,
  //       resourceIcon: null,
  //       resourceKey: 'rfqDetail',
  //       resourceName: 'RFQ Detail',
  //       title: 'RFQ Detail',
  //       resourceStatus: 0,
  //       resourceStatusText: '正常',
  //       resourceUrl: null,
  //       orderNum: 0,
  //       parentId: 36,
  //       children: null,
  //       resourceType: 0,
  //       resourceTypeText: '页面',
  //     },
  //     {
  //       version: null,
  //       resourceId: 146,
  //       value: 146,
  //       resourceIcon: null,
  //       resourceKey: 'rfqQuote',
  //       resourceName: 'RFQ Quote',
  //       title: 'RFQ Quote',
  //       resourceStatus: 0,
  //       resourceStatusText: '正常',
  //       resourceUrl: null,
  //       orderNum: 0,
  //       parentId: 36,
  //       children: null,
  //       resourceType: 0,
  //       resourceTypeText: '页面',
  //     },
  //   ],
  //   resourceType: 0,
  //   resourceTypeText: '页面',
  // },
  // {
  //   version: null,
  //   resourceId: 37,
  //   value: 37,
  //   resourceIcon: null,
  //   resourceKey: 'po',
  //   resourceName: 'PO Management',
  //   title: 'PO Management',
  //   resourceStatus: 0,
  //   resourceStatusText: '正常',
  //   resourceUrl: '/POManagement',
  //   orderNum: 4,
  //   parentId: 0,
  //   children: [
  //     {
  //       version: null,
  //       resourceId: 147,
  //       value: 147,
  //       resourceIcon: null,
  //       resourceKey: 'poList',
  //       resourceName: 'PO List',
  //       title: 'PO List',
  //       resourceStatus: 0,
  //       resourceStatusText: '正常',
  //       resourceUrl: null,
  //       orderNum: 0,
  //       parentId: 37,
  //       children: null,
  //       resourceType: 0,
  //       resourceTypeText: '页面',
  //     },
  //     {
  //       version: null,
  //       resourceId: 148,
  //       value: 148,
  //       resourceIcon: null,
  //       resourceKey: 'poDetail',
  //       resourceName: 'PO Detail',
  //       title: 'PO Detail',
  //       resourceStatus: 0,
  //       resourceStatusText: '正常',
  //       resourceUrl: null,
  //       orderNum: 0,
  //       parentId: 37,
  //       children: null,
  //       resourceType: 0,
  //       resourceTypeText: '页面',
  //     },
  //   ],
  //   resourceType: 0,
  //   resourceTypeText: '页面',
  // },
  // {
  //   version: null,
  //   resourceId: 133,
  //   value: 133,
  //   resourceIcon: null,
  //   resourceKey: 'qc',
  //   resourceName: 'Quality Control',
  //   title: 'Quality Control',
  //   resourceStatus: 0,
  //   resourceStatusText: '正常',
  //   resourceUrl: 'http://www.com',
  //   orderNum: 4,
  //   parentId: 0,
  //   children: [
  //     {
  //       version: null,
  //       resourceId: 149,
  //       value: 149,
  //       resourceIcon: null,
  //       resourceKey: 'qcList',
  //       resourceName: 'QC List',
  //       title: 'QC List',
  //       resourceStatus: 0,
  //       resourceStatusText: '正常',
  //       resourceUrl: null,
  //       orderNum: 0,
  //       parentId: 133,
  //       children: null,
  //       resourceType: 0,
  //       resourceTypeText: '页面',
  //     },
  //     {
  //       version: null,
  //       resourceId: 150,
  //       value: 150,
  //       resourceIcon: null,
  //       resourceKey: 'qcDetail',
  //       resourceName: 'QC Detail',
  //       title: 'QC Detail',
  //       resourceStatus: 0,
  //       resourceStatusText: '正常',
  //       resourceUrl: null,
  //       orderNum: 0,
  //       parentId: 133,
  //       children: null,
  //       resourceType: 0,
  //       resourceTypeText: '页面',
  //     },
  //   ],
  //   resourceType: 0,
  //   resourceTypeText: '页面',
  // },
  // {
  //   version: null,
  //   resourceId: 38,
  //   value: 38,
  //   resourceIcon: null,
  //   resourceKey: 'sample',
  //   resourceName: 'Sample Management',
  //   title: 'Sample Management',
  //   resourceStatus: 0,
  //   resourceStatusText: '正常',
  //   resourceUrl: '/SampleManagement',
  //   orderNum: 5,
  //   parentId: 0,
  //   children: null,
  //   resourceType: 0,
  //   resourceTypeText: '页面',
  // },
  // {
  //   version: null,
  //   resourceId: 151,
  //   value: 151,
  //   resourceIcon: null,
  //   resourceKey: 'sampleDetail',
  //   resourceName: 'Sample Detail',
  //   title: 'Sample Detail',
  //   resourceStatus: 0,
  //   resourceStatusText: '正常',
  //   resourceUrl: null,
  //   orderNum: 5,
  //   parentId: 0,
  //   children: null,
  //   resourceType: 0,
  //   resourceTypeText: '页面',
  // },
  // {
  //   version: null,
  //   resourceId: 39,
  //   value: 39,
  //   resourceIcon: null,
  //   resourceKey: 'expo',
  //   resourceName: 'Expo Management',
  //   title: 'Expo Management',
  //   resourceStatus: 0,
  //   resourceStatusText: '正常',
  //   resourceUrl: '/',
  //   orderNum: 6,
  //   parentId: 0,
  //   children: [
  //     {
  //       version: null,
  //       resourceId: 40,
  //       value: 40,
  //       resourceIcon: null,
  //       resourceKey: 'expoList',
  //       resourceName: 'My Expo',
  //       title: 'My Expo',
  //       resourceStatus: 0,
  //       resourceStatusText: '正常',
  //       resourceUrl: '/ExpoManagement/MyExpo',
  //       orderNum: 0,
  //       parentId: 39,
  //       children: null,
  //       resourceType: 0,
  //       resourceTypeText: '页面',
  //     },
  //     {
  //       version: null,
  //       resourceId: 41,
  //       value: 41,
  //       resourceIcon: null,
  //       resourceKey: 'expoProductList',
  //       resourceName: 'Expo Application',
  //       title: 'Expo Application',
  //       resourceStatus: 0,
  //       resourceStatusText: '正常',
  //       resourceUrl: '/ExpoManagement/ExpoApplication',
  //       orderNum: 1,
  //       parentId: 39,
  //       children: null,
  //       resourceType: 0,
  //       resourceTypeText: '页面',
  //     },
  //   ],
  //   resourceType: 0,
  //   resourceTypeText: '页面',
  // },
  // {
  //   version: null,
  //   resourceId: 42,
  //   value: 42,
  //   resourceIcon: null,
  //   resourceKey: 'favoriteList',
  //   resourceName: 'Favorites',
  //   title: 'Favorites',
  //   resourceStatus: 0,
  //   resourceStatusText: '正常',
  //   resourceUrl: '/Favorites',
  //   orderNum: 7,
  //   parentId: 0,
  //   children: null,
  //   resourceType: 0,
  //   resourceTypeText: '页面',
  // },
  // {
  //   version: null,
  //   resourceId: 197,
  //   value: 197,
  //   resourceIcon: null,
  //   resourceKey: 'auth',
  //   resourceName: 'Auth Management',
  //   title: 'Auth Management',
  //   resourceStatus: 0,
  //   resourceStatusText: '正常',
  //   resourceUrl: '/',
  //   orderNum: 7,
  //   parentId: 0,
  //   children: [
  //     {
  //       version: null,
  //       resourceId: 198,
  //       value: 198,
  //       resourceIcon: null,
  //       resourceKey: 'role',
  //       resourceName: 'Role Management',
  //       title: 'Role Management',
  //       resourceStatus: 0,
  //       resourceStatusText: '正常',
  //       resourceUrl: '/roleManage',
  //       orderNum: 0,
  //       parentId: 197,
  //       children: null,
  //       resourceType: 0,
  //       resourceTypeText: '页面',
  //     },
  //     {
  //       version: null,
  //       resourceId: 199,
  //       value: 199,
  //       resourceIcon: null,
  //       resourceKey: 'user',
  //       resourceName: 'User Management',
  //       title: 'User Management',
  //       resourceStatus: 0,
  //       resourceStatusText: '正常',
  //       resourceUrl: '/userManage',
  //       orderNum: 1,
  //       parentId: 197,
  //       children: null,
  //       resourceType: 0,
  //       resourceTypeText: '页面',
  //     },
  //   ],
  //   resourceType: 0,
  //   resourceTypeText: '页面',
  // },
  // {
  //   version: null,
  //   resourceId: 152,
  //   value: 152,
  //   resourceIcon: null,
  //   resourceKey: 'decoration',
  //   resourceName: 'Website Management',
  //   title: 'Website Management',
  //   resourceStatus: 0,
  //   resourceStatusText: '正常',
  //   resourceUrl: null,
  //   orderNum: 8,
  //   parentId: 0,
  //   children: [
  //     {
  //       version: null,
  //       resourceId: 153,
  //       value: 153,
  //       resourceIcon: null,
  //       resourceKey: 'websiteDecoration',
  //       resourceName: 'Website Decoration',
  //       title: 'Website Decoration',
  //       resourceStatus: 0,
  //       resourceStatusText: '正常',
  //       resourceUrl: null,
  //       orderNum: 0,
  //       parentId: 152,
  //       children: null,
  //       resourceType: 0,
  //       resourceTypeText: '页面',
  //     },
  //     {
  //       version: null,
  //       resourceId: 154,
  //       value: 154,
  //       resourceIcon: null,
  //       resourceKey: 'showroomDecoration',
  //       resourceName: 'ShowroomDecoration',
  //       title: 'ShowroomDecoration',
  //       resourceStatus: 0,
  //       resourceStatusText: '正常',
  //       resourceUrl: null,
  //       orderNum: 1,
  //       parentId: 152,
  //       children: null,
  //       resourceType: 0,
  //       resourceTypeText: '页面',
  //     },
  //   ],
  //   resourceType: 0,
  //   resourceTypeText: '页面',
  // },
  // {
  //   version: null,
  //   resourceId: 200,
  //   value: 200,
  //   resourceIcon: null,
  //   resourceKey: 'accountDetail',
  //   resourceName: 'Account Management',
  //   title: 'Account Management',
  //   resourceStatus: 0,
  //   resourceStatusText: '正常',
  //   resourceUrl: '/accountManage',
  //   orderNum: 8,
  //   parentId: 0,
  //   children: null,
  //   resourceType: 0,
  //   resourceTypeText: '页面',
  // },
  // {
  //   version: null,
  //   resourceId: 46,
  //   value: 46,
  //   resourceIcon: null,
  //   resourceKey: 'company',
  //   resourceName: 'My Company',
  //   title: 'My Company',
  //   resourceStatus: 0,
  //   resourceStatusText: '正常',
  //   resourceUrl: '/MyCompany',
  //   orderNum: 10,
  //   parentId: 0,
  //   children: [
  //     {
  //       version: null,
  //       resourceId: 155,
  //       value: 155,
  //       resourceIcon: null,
  //       resourceKey: 'companyProfile',
  //       resourceName: 'Company Profile',
  //       title: 'Company Profile',
  //       resourceStatus: 0,
  //       resourceStatusText: '正常',
  //       resourceUrl: null,
  //       orderNum: 0,
  //       parentId: 46,
  //       children: null,
  //       resourceType: 0,
  //       resourceTypeText: '页面',
  //     },
  //     {
  //       version: null,
  //       resourceId: 156,
  //       value: 156,
  //       resourceIcon: null,
  //       resourceKey: 'companyEditVerification',
  //       resourceName: 'EditVerification',
  //       title: 'EditVerification',
  //       resourceStatus: 0,
  //       resourceStatusText: '正常',
  //       resourceUrl: null,
  //       orderNum: 0,
  //       parentId: 46,
  //       children: null,
  //       resourceType: 0,
  //       resourceTypeText: '页面',
  //     },
  //     {
  //       version: null,
  //       resourceId: 157,
  //       value: 157,
  //       resourceIcon: null,
  //       resourceKey: 'companyEditProfile',
  //       resourceName: 'EditProfile',
  //       title: 'EditProfile',
  //       resourceStatus: 0,
  //       resourceStatusText: '正常',
  //       resourceUrl: null,
  //       orderNum: 0,
  //       parentId: 46,
  //       children: null,
  //       resourceType: 0,
  //       resourceTypeText: '页面',
  //     },
  //     {
  //       version: null,
  //       resourceId: 158,
  //       value: 158,
  //       resourceIcon: null,
  //       resourceKey: 'companyEditQualityChina',
  //       resourceName: 'EditQualityChina',
  //       title: 'EditQualityChina',
  //       resourceStatus: 0,
  //       resourceStatusText: '正常',
  //       resourceUrl: null,
  //       orderNum: 0,
  //       parentId: 46,
  //       children: null,
  //       resourceType: 0,
  //       resourceTypeText: '页面',
  //     },
  //     {
  //       version: null,
  //       resourceId: 159,
  //       value: 159,
  //       resourceIcon: null,
  //       resourceKey: 'companyVerification',
  //       resourceName: 'Verification',
  //       title: 'Verification',
  //       resourceStatus: 0,
  //       resourceStatusText: '正常',
  //       resourceUrl: null,
  //       orderNum: 0,
  //       parentId: 46,
  //       children: null,
  //       resourceType: 0,
  //       resourceTypeText: '页面',
  //     },
  //   ],
  //   resourceType: 0,
  //   resourceTypeText: '页面',
  // },
  // {
  //   version: null,
  //   resourceId: 47,
  //   value: 47,
  //   resourceIcon: null,
  //   resourceKey: 'messageList',
  //   resourceName: 'Message',
  //   title: 'Message',
  //   resourceStatus: 0,
  //   resourceStatusText: '正常',
  //   resourceUrl: '/Message',
  //   orderNum: 11,
  //   parentId: 0,
  //   children: null,
  //   resourceType: 0,
  //   resourceTypeText: '页面',
  // },
  // {
  //   version: null,
  //   resourceId: 160,
  //   value: 160,
  //   resourceIcon: null,
  //   resourceKey: 'accountManage',
  //   resourceName: 'Account',
  //   title: 'Account',
  //   resourceStatus: 0,
  //   resourceStatusText: '正常',
  //   resourceUrl: 'https://sso.test.yeeorder.com.cn/accountManage',
  //   orderNum: 12,
  //   parentId: 0,
  //   children: null,
  //   resourceType: 0,
  //   resourceTypeText: '页面',
  // },
];
